api_platform:
    version: '1.0.0'
    collection:
        pagination:
            items_per_page: 2 
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    
    
